export const CurrencyQuotesDto = {
	AED: "Dirham dos Emirados Árabes Unidos (AED)",
	AFN: "Afegane Afegão (AFN)",
	ALL: "Lek Albanês (ALL)",
	AMD: "Dram Armênio (AMD)",
	ANG: "Florim das Antilhas Holandesas (ANG)",
	AOA: "Kwanza Angolano (AOA)",
	ARS: "Peso Argentino (ARS)",
	AUD: "Dólar Australiano (AUD)",
	AWG: "Florim Arubano (AWG)",
	AZN: "Manat Azeri (AZN)",
	BAM: "Marco Conversível da Bósnia-Herzegovina (BAM)",
	BBD: "Dólar de Barbados (BBD)",
	BDT: "Taka de Bangladesh (BDT)",
	BGN: "Lev Búlgaro (BGN)",
	BHD: "Dinar do Bahrein (BHD)",
	BIF: "Franco Burundiano (BIF)",
	BMD: "Dólar das Bermudas (BMD)",
	BND: "Dólar de Brunei (BND)",
	BOB: "Boliviano da Bolívia (BOB)",
	BRL: "Real Brasileiro (BRL)",
	BSD: "Dólar das Bahamas (BSD)",
	BTC: "Bitcoin (BTC)",
	BTN: "Ngultrum do Butão (BTN)",
	BTS: "BitShares (BTS)",
	BWP: "Pula de Botswana (BWP)",
	BYN: "Rublo Bielorrusso (BYN)",
	BZD: "Dólar de Belize (BZD)",
	CAD: "Dólar Canadense (CAD)",
	CDF: "Franco Congolês (CDF)",
	CHF: "Franco Suíço (CHF)",
	CLF: "Unidade de Conta Chilena (CLF)",
	CLP: "Peso Chileno (CLP)",
	CNH: "Yuan Chinês (Offshore) (CNH)",
	CNY: "Yuan Chinês (CNY)",
	COP: "Peso Colombiano (COP)",
	CRC: "Colón Costarriquenho (CRC)",
	CUC: "Peso Cubano Conversível (CUC)",
	CUP: "Peso Cubano (CUP)",
	CVE: "Escudo Cabo-Verdiano (CVE)",
	CZK: "Coroa Checa (CZK)",
	DASH: "Dash (DASH)",
	DJF: "Franco Djiboutiano (DJF)",
	DKK: "Coroa Dinamarquesa (DKK)",
	DOGE: "Dogecoin (DOGE)",
	DOP: "Peso Dominicano (DOP)",
	DZD: "Dinar Argelino (DZD)",
	EGP: "Libra Egípcia (EGP)",
	ERN: "Nakfa da Eritreia (ERN)",
	ETB: "Birr Etíope (ETB)",
	ETH: "Ethereum (ETH)",
	EUR: "Euro (EUR)",
	FJD: "Dólar Fijiano (FJD)",
	FKP: "Libra das Ilhas Falkland (FKP)",
	GBP: "Libra Esterlina (GBP)",
	GEL: "Lari Georgiano (GEL)",
	GGP: "Libra de Guernsey (GGP)",
	GHS: "Cedi Ganês (GHS)",
	GIP: "Libra de Gibraltar (GIP)",
	GMD: "Dalasi da Gâmbia (GMD)",
	GNF: "Franco Guineano (GNF)",
	GTQ: "Quetzal Guatemalteco (GTQ)",
	GYD: "Dólar da Guiana (GYD)",
	HKD: "Dólar de Hong Kong (HKD)",
	HNL: "Lempira Hondurenha (HNL)",
	HRK: "Kuna Croata (HRK)",
	HTG: "Gourde Haitiano (HTG)",
	HUF: "Florim Húngaro (HUF)",
	IDR: "Rupia Indonésia (IDR)",
	ILS: "Novo Shekel Israelense (ILS)",
	IMP: "Libra da Ilha de Man (IMP)",
	INR: "Rupia Indiana (INR)",
	IQD: "Dinar Iraquiano (IQD)",
	IRR: "Rial Iraniano (IRR)",
	ISK: "Coroa Islandesa (ISK)",
	JEP: "Libra de Jersey (JEP)",
	JMD: "Dólar Jamaicano (JMD)",
	JOD: "Dinar Jordaniano (JOD)",
	JPY: "Iene Japonês (JPY)",
	KES: "Xelim Queniano (KES)",
	KGS: "Som Quirguiz (KGS)",
	KHR: "Riel Cambojano (KHR)",
	KMF: "Franco Comorense (KMF)",
	KPW: "Won Norte-Coreano (KPW)",
	KRW: "Won Sul-Coreano (KRW)",
	KWD: "Dinar Kuwaitiano (KWD)",
	KYD: "Dólar das Ilhas Cayman (KYD)",
	KZT: "Tenge Cazaque (KZT)",
	LAK: "Kip Laosiano (LAK)",
	LBP: "Libra Libanesa (LBP)",
	LD: "Dólar Linden (LD)",
	LKR: "Rupia do Sri Lanka (LKR)",
	LRD: "Dólar Liberiano (LRD)",
	LSL: "Loti do Lesoto (LSL)",
	LTC: "Litecoin (LTC)",
	LYD: "Dinar Líbio (LYD)",
	MAD: "Dirham Marroquino (MAD)",
	MDL: "Leu Moldavo (MDL)",
	MGA: "Ariary Malgaxe (MGA)",
	MKD: "Dinar Macedônio (MKD)",
	MMK: "Kyat de Mianmar (MMK)",
	MNT: "Tugrik Mongol (MNT)",
	MOP: "Pataca de Macau (MOP)",
	MRO: "Ouguiya Mauritana (MRO)",
	MRU: "Ouguiya Mauritana (MRU)",
	MUR: "Rupia Mauriciana (MUR)",
	MVR: "Rufiyaa Maldiva (MVR)",
	MWK: "Kwacha Malauiana (MWK)",
	MXN: "Peso Mexicano (MXN)",
	MYR: "Ringgit Malaio (MYR)",
	MZN: "Metical Moçambicano (MZN)",
	NAD: "Dólar Namibiano (NAD)",
	NGN: "Naira Nigeriana (NGN)",
	NIO: "Córdoba Nicaraguense (NIO)",
	NOK: "Coroa Norueguesa (NOK)",
	NPR: "Rupia Nepalesa (NPR)",
	NXT: "Nxt (NXT)",
	NZD: "Dólar Neozelandês (NZD)",
	OMR: "Rial Omanense (OMR)",
	PAB: "Balboa Panamenho (PAB)",
	PEN: "Novo Sol Peruano (PEN)",
	PGK: "Kina Papua-Nova Guiné (PGK)",
	PHP: "Peso Filipino (PHP)",
	PKR: "Rupia Paquistanesa (PKR)",
	PLN: "Zloty Polonês (PLN)",
	PYG: "Guarani Paraguaio (PYG)",
	QAR: "Rial Catarense (QAR)",
	RON: "Leu Romeno (RON)",
	RSD: "Dinar Sérvio (RSD)",
	RUB: "Rublo Russo (RUB)",
	RWF: "Franco Ruandês (RWF)",
	SAR: "Riyal Saudita (SAR)",
	SBD: "Dólar das Ilhas Salomão (SBD)",
	SCR: "Rupia de Seicheles (SCR)",
	SDG: "Libra Sudanesa (SDG)",
	SEK: "Coroa Sueca (SEK)",
	SGD: "Dólar de Singapura (SGD)",
	SHP: "Libra de Santa Helena (SHP)",
	SLL: "Leone de Serra Leoa (SLL)",
	SOS: "Xelim Somali (SOS)",
	SRD: "Dólar do Suriname (SRD)",
	SSP: "Libra do Sudão do Sul (SSP)",
	STD: "Dobra de São Tomé e Príncipe (STD)",
	STN: "Dobra de São Tomé e Príncipe (STN)",
	STR: "Stellar (STR)",
	SVC: "Colón Salvadorenho (SVC)",
	SYP: "Libra Síria (SYP)",
	SZL: "Lilangeni Suazi (SZL)",
	THB: "Baht Tailandês (THB)",
	TJS: "Somoni do Tajiquistão (TJS)",
	TMT: "Manat Turcomeno (TMT)",
	TND: "Dinar Tunisiano (TND)",
	TOP: "Paʻanga de Tonga (TOP)",
	TRY: "Lira Turca (TRY)",
	TTD: "Dólar de Trinidad e Tobago (TTD)",
	TWD: "Novo Dólar Taiwanês (TWD)",
	TZS: "Xelim Tanzaniano (TZS)",
	UAH: "Hryvnia Ucraniana (UAH)",
	UGX: "Xelim Ugandense (UGX)",
	USD: "Dólar dos Estados Unidos (USD)",
	UYU: "Peso Uruguaio (UYU)",
	UZS: "Som Uzbeque (UZS)",
	VES: "Bolívar Venezuelano Soberano (VES)",
	VND: "Dong Vietnamita (VND)",
	VUV: "Vatu de Vanuatu (VUV)",
	WST: "Tala Samoano (WST)",
	XAF: "Franco CFA BEAC (XAF)",
	XAG: "Onça de Prata (XAG)",
	XAU: "Onça de Ouro (XAU)",
	XCD: "Dólar do Caribe Oriental (XCD)",
	XDR: "Direitos Especiais de Saque (XDR)",
	XMR: "Monero (XMR)",
	XOF: "Franco CFA BCEAO (XOF)",
	XPD: "Onça de Paládio (XPD)",
	XPF: "Franco CFP (XPF)",
	XPT: "Onça de Platina (XPT)",
	XRP: "XRP (XRP)",
	YER: "Rial Iemenita (YER)",
	ZAR: "Rand Sul-Africano (ZAR)",
	ZMW: "Kwacha Zambiano (ZMW)",
	ZWL: "Dólar Zimbabuano (ZWL)",
	NMC: "Namecoin (NMC)",
	PPC: "Peercoin (PPC)",
	NVC: "Novacoin (NVC)",
	XPM: "Primecoin (XPM)",
	EAC: "EarthCoin (EAC)",
	VTC: "Vertcoin (VTC)",
	EMC: "Emercoin (EMC)",
	FCT: "Factom (FCT)",
};
