export type Sort =
	| "name"
	| "symbol"
	| "date_added"
	| "market_cap"
	| "market_cap_strict"
	| "price"
	| "circulating_supply"
	| "total_supply"
	| "max_supply"
	| "num_market_pairs"
	| "volume_24h"
	| "percent_change_1h"
	| "percent_change_24h"
	| "percent_change_7d"
	| "market_cap_by_total_supply_strict"
	| "volume_7d"
	| " volume_30d";
